#!/bin/bash
# Setup pre-commit hook for dependency analysis

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
GIT_HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
ANALYSIS_DIR="$PROJECT_ROOT/.claude/analysis"
PYTHON_SCRIPT="$ANALYSIS_DIR/analyze-dependencies.py"

echo "🔧 Setting up dependency analysis pre-commit hook..."
echo ""

# Create hooks directory if it doesn't exist
mkdir -p "$GIT_HOOKS_DIR"

# Create pre-commit hook
PRE_COMMIT_HOOK="$GIT_HOOKS_DIR/pre-commit"

cat > "$PRE_COMMIT_HOOK" << 'HOOK_EOF'
#!/bin/bash
# Pre-commit hook: Auto-generate dependency snapshots

set -e

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
ANALYSIS_DIR="$PROJECT_ROOT/.claude/analysis"
HISTORY_DIR="$ANALYSIS_DIR/history"
PYTHON_SCRIPT="$ANALYSIS_DIR/analyze-dependencies.py"

# Ensure directories exist
mkdir -p "$HISTORY_DIR"

# Get current git info before commit
COMMIT_HASH=$(git rev-parse --short HEAD)
TIMESTAMP=$(date +%s)
DATE=$(date +"%Y-%m-%d %H:%M:%S")

# Run analyzer
if [ ! -f "$PYTHON_SCRIPT" ]; then
    echo "⚠️  Warning: Dependency analyzer not found at $PYTHON_SCRIPT"
    exit 0
fi

echo "🔍 Analyzing dependencies..."
cd "$PROJECT_ROOT"

# Run the analysis (which now includes visualization)
python3 "$PYTHON_SCRIPT" 2>/dev/null || {
    echo "⚠️  Warning: Dependency analysis failed (continuing anyway)"
    exit 0
}

# Note: Diagrams are auto-generated by analyze-dependencies.py

# Save snapshot with commit metadata
SNAPSHOT_FILE="$HISTORY_DIR/${COMMIT_HASH}.json"

if [ -f "$ANALYSIS_DIR/dependency-map.json" ]; then
    # Use Python to add metadata and save
    python3 << PYTHON_EOF
import json
from pathlib import Path
from datetime import datetime

try:
    analysis_dir = Path("$ANALYSIS_DIR")
    history_dir = Path("$HISTORY_DIR")

    # Read the generated map
    with open(analysis_dir / "dependency-map.json", "r") as f:
        data = json.load(f)

    # Add git metadata
    data["metadata"] = {
        "git_commit": "$COMMIT_HASH",
        "timestamp": $TIMESTAMP,
        "date": "$DATE"
    }

    # Write snapshot
    history_dir.mkdir(parents=True, exist_ok=True)
    with open(history_dir / "${COMMIT_HASH}.json", "w") as f:
        json.dump(data, f, indent=2)

    print(f"✅ Snapshot saved: {history_dir}/${COMMIT_HASH}.json")
except Exception as e:
    print(f"⚠️  Failed to save snapshot: {e}")
    exit(0)
PYTHON_EOF
fi

exit 0
HOOK_EOF

# Make hook executable
chmod +x "$PRE_COMMIT_HOOK"

echo "✅ Pre-commit hook installed at: $PRE_COMMIT_HOOK"
echo ""
echo "📋 Next steps:"
echo "  1. Your next commit will automatically generate a dependency snapshot"
echo "  2. View snapshots: python3 $ANALYSIS_DIR/snapshot-manager.py list"
echo "  3. Compare commits: python3 $ANALYSIS_DIR/snapshot-manager.py compare <commit1> [commit2]"
echo "  4. Read docs: cat $ANALYSIS_DIR/README.md"
echo ""
echo "🎯 To test:"
echo "  cd $PROJECT_ROOT"
echo "  git add .claude/analysis/"
echo "  git commit -m 'chore: add dependency analysis system'"
echo ""
